sudo: require
services: 
  - docker

before_install:
  - docker build -t mreis43/docker-react -f Dockerfile.dev  .

script:
  - docker run mreis43/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-React"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-850960240956"
  bucker_patch: "Docker-React"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
